sudo: required
services:
  - docker

before_install:
  - docker build -t clovethrowd916/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true clovethrowd916/docker-react npm run test
language: generic

deploy:
  provider: azure_web_apps
